version: "3.8"
services:
  back-llm:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - type: bind
        source: $MODELS_DIRECTORY 
        target: /home/dev/models
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

